export const StockActiontype=
{
    ADD_STOCK_REQUEST:"ADD_STOCK_REQUEST",
    ADD_STOCK_SUCCESS:"ADD_STOCK_SUCCESS",
    ADD_STOCK_FAIL:"ADD_STOCK_FAIL",
    GET_STOCK_REQUEST:"GET_STOCK_REQUEST",
    GET_STOCK_SUCCESS:"GET_STOCK_SUCCESS",
    GET_STOCK_FAIL:"GET_STOCK_REQUEST",
    DELETE_STOCK_REQUEST:"DELETE_STOCK_REQUEST",
    DELETE_STOCK_SUCCESS:"DELETE_STOCK_SUCCESS",
    DELETE_STOCK_FAIL:"DELETE_STOCK_FAIL"

}

export const OrderActiontype=
{
    ADD_ORDER_REQUEST:"ADD_ORDER_REQUEST",
    ADD_ORDER_SUCCESS:"ADD_ORDER_SUCCESS",
    ADD_ORDER_FAIL: "ADD_ORDER_FAIL",
    GET_ORDER_REQUEST:"GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS:"GET_ORDER_SUCCESS",
    GET_ORDER_FAIL:"GET_ORDER_FAIL",
    DELET_ORDER_REQUEST:"DELET_ORDER_REQUEST",
    DELET_ORDER_SUCCESS:"DELET_ORDER_SUCCESS",
    DELET_ORDER_FAIL:"DELET_ORDER_FAIL"

}