export const BlogActionTypes=
{
    ADD_REQUEST:"ADD_REQUEST",
    ADD_SUCCESS:"ADD_SUCCESS",
    ADD_FAIL:"ADD_FAIL",
    FETCH_REQUEST:"FETCH_REQUEST",
    FETCH_SUCCESS:"FETCH_SUCCESS",
    FETCH_FAIL:"FETCH_FAIL",
    DELETE_REQUEST:"DELETE_REQUEST",
    DELETE_SUCCESS:"DELETE_SUCCESS",
    DELETE_FAIL:"DELETE_SUCCESS",
    FETCH_SINGLE_REQUEST:"FETCH_SINGLE_REQUEST",
    FETCH_SINGLE_SUCCESS:"FETCH_SINGLE_SUCCESS",
    FETCH_SINGLE_FAIL:"FETCH_SINGLE_FAIL",
    UPDATE_REQUEST:"UPDATE_REQUEST",
    UPDATE_SUCCESS:"UPDATE_SUCCESS",
    UPDATE_FAIL:"UPDATE_FAIL"
}