export const BlogActionTypes=
{
    ADD_REQUEST:"ADD_REQUEST",
    ADD_SUCCESS:"ADD_SUCCESS",
    ADD_FAIL:"ADD_FAIL",
    FETCH_REQUEST:"FETCH_REQUEST",
    FETCH_SUCCESS:"FETCH_SUCCESS",
    FETCH_FAIL:"FETCH_FAIL",
    DELETE_REQUEST:"DELETE_REQUEST",
    DELETE_SUCCESS:"DELETE_SUCCESS",
    DELETE_FAIL:"DELETE_SUCCESS",
    FETCH_SINGLE_REQUEST:"FETCH_SINGLE_REQUEST",
    FETCH_SINGLE_SUCCESS:"FETCH_SINGLE_SUCCESS",
    FETCH_SINGLE_FAIL:"FETCH_SINGLE_FAIL",
    UPDATE_REQUEST:"UPDATE_REQUEST",
    UPDATE_SUCCESS:"UPDATE_SUCCESS",
    UPDATE_FAIL:"UPDATE_FAIL"
}

export const UserActionsType={
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAIL:"SIGNUP_FAIL",
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL:"LOGIN_FAIL",
    FETCHALL_USERS_REQUEST:"FETCHALL_USERS_REQUEST",
    FETCHALL_USERS_SUCCESS:"FETCHALL_USERS_SUCCESS",
    FETCHALL_USERS_FAIL:"FETCHALL_USERS_FAIL",
    DELETE_USER_REQUEST:"DELETE_USER_REQUEST",
    DELETE_USER_SUCCESS:"DELETE_USER_SUCCESS",
    DELETE_USER_FAIL:"DELETE_USER_FAIL",
    FETCH_PROFILE_REQUEST:"FETCH_PROFILE_REQUEST",
    FETCH_PROFILE_SUCCESS:"FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_FAIL:"FETCH_PROFILE_FAIL",
    UPDATE_PROFILE_REQUEST:"UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS:"UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAIL:"UPDATE_PROFILE_FAIL",
    FETCH_OWN_PROFILE_REQUEST:"FETCH_OWN_PROFILE_REQUEST",
    FETCH_OWN_PROFILE_SUCCESS:"FETCH_OWN_PROFILE_SUCCESS",
    FETCH_OWN_PROFILE_FAIL:"FETCH_OWN_PROFILE_FAIL",
}

export const AdminAction_type={
    FETCH_PERMISSION_REQUEST:"FETCH_PERMISSION_REQUEST",
    FETCH_PERMISSION_SUCCESS:"FETCH_PERMISSION_SUCCESS",
    FETCH_PERMISSION_FAIL:"FETCH_PERMISSION_FAIL",
    ADD_ROLE_REQUEST:"ADD_ROLE_REQUEST",
    ADD_ROLE_SUCCESS:"ADD_ROLE_SUCCESS",
    ADD_ROLE_FAIL:"ADD_ROLE_FAIL",
    FETCH_ROLE_REQUEST:"FETCH_ROLE_REQUEST",
    FETCH_ROLE_SUCCESS:"FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAIL:"FETCH_ROLE_FAIL"
}