export const UserActionTypes=
{
    USER_REGISTRATION_REQUEST:"USER_REGISTRATION_REQUEST",
    USER_REGISTRATION_SUCCESS:"USER_REGISTRATION_SUCCESS",
    USER_REGISTRATION_FAIL:"USER_REGISTRATION_FAIL",
    USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL:"USER_LOGIN_FAIL",
    VIEW_PROFILE_REQUEST:"VIEW_PROFILE_REQUEST",
    VIEW_PROFILE_SUCCESS:"VIEW_PROFILE_SUCCESS",
    VIEW_PROFILE_FAIL:"VIEW_PROFILE_FAIL",
    UPDATE_PROFILE_REQUEST:"UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS:"UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAIL:"UPDATE_PROFILE_FAIL"
    
}