export const UserActionTypes=
{
    USER_REGISTRATION_REQUEST:"USER_REGISTRATION_REQUEST",
    USER_REGISTRATION_SUCCESS:"USER_REGISTRATION_SUCCESS",
    USER_REGISTRATION_FAIL:"USER_REGISTRATION_FAIL",
    USER_LOGIN_REQUEST:"USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL:"USER_LOGIN_FAIL",
    VIEW_PROFILE_REQUEST:"VIEW_PROFILE_REQUEST",
    VIEW_PROFILE_SUCCESS:"VIEW_PROFILE_SUCCESS",
    VIEW_PROFILE_FAIL:"VIEW_PROFILE_FAIL",
    UPDATE_PROFILE_REQUEST:"UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS:"UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAIL:"UPDATE_PROFILE_FAIL"
    
}

export const suppillerActiontypes=
{
    FETCH_SUPPILLERS_REQUEST:"FETCH_SUPPILLERS_REQUEST",
    FETCH_SUPPILLERS_SUCCESS:"FETCH_SUPPILLERS_SUCCESS",
    FETCH_SUPPILLERS_FAIL:"FETCH_SUPPILLERS_FAIL",
    POST_DATA_REQUEST:"POST_DATA_REQUEST",
    POST_DATA_SUCCESS:"POST_DATA_SUCCESS",
    POST_DATA_FAIL:"POST_DATA_FAIL"
}

export const HeaderActiontype=
{
    FETCH_HEADER_REQUEST:"FETCH_HEADER_REQUEST",
    FETCH_HEADER_SUCCESS:"FETCH_HEADER_SUCCESS",
    FETCH_HEADER_FAIL:"FETCH_HEADER_FAIL",
    POST_HEADER_REQUEST:"POST_HEADER_REQUEST",
    POST_HEADER_SUCCESS:"POST_HEADER_SUCCESS",
    POST_HEADER_FAIL:"POST_HEADER_FAIL"
    
}